# Configure connection with S3 buckets

s3:
  access_key: 'AWS_ACCESS_KEY_ID'
  secret_key: 'AWS_SECRET_ACCESS_KEY'
  src_endpoint_url: 'https://s3.eu-central-1.amazonaws.com'
  src_bucket: 'xetra-1234'
  trg_endpoint_url: 'https://s3.eu-central-1.amazonaws.com'
  trg_bucket: 'xetra-piotr'


# Source data configuration

source:
  first_extract_date: '2021-02-02'
  columns: [ 'ISIN', 'Mnemonic', 'Date', 'Time', 'StartPrice', 'EndPrice', 'MinPrice', 'MaxPrice', 'TradedVolume' ]
  col_date: 'Date'
  col_isin: 'ISIN'
  col_time: 'Time'
  col_min_price: 'MinPrice'
  col_start_price: 'StartPrice'
  col_end_price: 'EndPrice'
  col_max_price: 'MaxPrice'
  col_traded_vol: 'TradedVolume'

# Target data configuration

target:
  key: 'report1/xetra_daily_report1_'
  key_date_format: '%Y%m%d_%H%M%S'
  format: 'parquet'
  col_isin: 'isin'
  col_date: 'date'
  col_opening_price: 'opening_price_eur'
  col_closing_price: 'closing_price_eur'
  col_min_price: 'minimum_price_eur'
  col_max_price: 'maximum_price_eur'
  col_daily_traded_volume: 'daily_traded_volume'
  col_change: 'change_prev_closing_%'

# Meta file configuration
meta:
  meta_key: 'meta/report1/xetra_report1_meta_file.csv'

# Logging configuration
logging:
  version: 1
  formatters:
    xetra:
      format: "Xetra Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: xetra
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]